import { Stock, WorkflowStep } from "@/types";

// Stock list extracted from n8n workflow
export const AVAILABLE_STOCKS: Stock[] = [
  { ticker: "PLTR", name: "Palantir Technologies Inc." },
  { ticker: "HOOD", name: "Robinhood Markets, Inc." },
  { ticker: "HIMS", name: "Hims & Hers Health, Inc." },
  { ticker: "APP", name: "AppLovin Corporation" },
  { ticker: "RKLB", name: "Rocket Lab USA, Inc." },
  { ticker: "TEM", name: "Tempus AI Inc." },
  { ticker: "SOFI", name: "SoFi Technologies, Inc." },
  { ticker: "OSCR", name: "Oscar Health, Inc." },
  { ticker: "IREN", name: "Iris Energy Limited" },
  { ticker: "NVDA", name: "NVIDIA Corporation" },
  { ticker: "BMNR", name: "Bitmine Immersion Technologies Inc." },
  { ticker: "SMCI", name: "Super Micro Computer, Inc." },
  { ticker: "LMND", name: "Lemonade, Inc." },
  { ticker: "CIFR", name: "Cipher Mining Inc." },
  { ticker: "CEG", name: "Constellation Energy Corporation" },
  { ticker: "ANET", name: "Arista Networks, Inc." },
  { ticker: "CLS", name: "Celestica Inc." },
  { ticker: "ORCL", name: "Oracle Corporation" },
  { ticker: "OPEN", name: "Opendoor Technologies Inc." },
  { ticker: "TSLA", name: "Tesla, Inc." },
  { ticker: "ZETA", name: "Zeta Global Holdings Corp." },
  { ticker: "RGTI", name: "Rigetti Computing, Inc." },
  { ticker: "ASTS", name: "AST SpaceMobile, Inc." },
  { ticker: "OKLO", name: "Oklo Inc." },
  { ticker: "AMD", name: "Advanced Micro Devices, Inc." },
  { ticker: "EOSE", name: "Eos Energy Enterprises, Inc." },
  { ticker: "IONQ", name: "IonQ, Inc." },
  { ticker: "CRWD", name: "CrowdStrike Holdings, Inc." },
  { ticker: "ASML", name: "ASML Holding N.V." },
  { ticker: "META", name: "Meta Platforms, Inc." },
  { ticker: "AVGO", name: "Broadcom Inc." },
  { ticker: "BA", name: "The Boeing Company" },
  { ticker: "AAPL", name: "Apple Inc." },
  { ticker: "MSFT", name: "Microsoft Corporation" },
  { ticker: "AMZN", name: "Amazon.com, Inc." },
  { ticker: "GOOG", name: "Alphabet Inc." },
  { ticker: "ADBE", name: "Adobe Inc." },
  { ticker: "MDB", name: "MongoDB, Inc." },
  { ticker: "MRVL", name: "Marvell Technology, Inc." },
  { ticker: "DDOG", name: "Datadog, Inc." },
  { ticker: "MSTR", name: "MicroStrategy Incorporated" },
  { ticker: "AXON", name: "Axon Enterprise, Inc." },
  { ticker: "UNH", name: "UnitedHealth Group Incorporated" },
  { ticker: "LLY", name: "Eli Lilly and Company" },
  { ticker: "ALAB", name: "Astera Labs, Inc." },
  { ticker: "CRM", name: "Salesforce, Inc." },
  { ticker: "DUOL", name: "Duolingo, Inc." },
  { ticker: "SE", name: "Sea Limited" },
  { ticker: "GRAB", name: "Grab Holdings Limited" },
  { ticker: "CELH", name: "Celsius Holdings, Inc." },
  { ticker: "CRDO", name: "Credo Technology Group Holding Ltd" },
  { ticker: "MU", name: "Micron Technology, Inc." },
  { ticker: "TTD", name: "The Trade Desk, Inc." },
  { ticker: "DLO", name: "DLocal Limited" },
  { ticker: "LEU", name: "Centrus Energy Corp." },
  { ticker: "SNOW", name: "Snowflake Inc." },
  { ticker: "COIN", name: "Coinbase Global, Inc." },
  { ticker: "V", name: "Visa Inc." },
  { ticker: "BKSY", name: "BlackSky Technology Inc." },
  { ticker: "AMPX", name: "Amprius Technologies, Inc." },
  { ticker: "NVTS", name: "Navitas Semiconductor Corporation" },
  { ticker: "JOBY", name: "Joby Aviation, Inc." },
  { ticker: "QUBT", name: "Quantum Computing Inc." },
  { ticker: "ABNB", name: "Airbnb, Inc." },
  { ticker: "BKNG", name: "Booking Holdings Inc." },
  { ticker: "MCHP", name: "Microchip Technology Incorporated" },
  { ticker: "NFLX", name: "Netflix, Inc." },
  { ticker: "PYPL", name: "PayPal Holdings, Inc." },
  { ticker: "QCOM", name: "QUALCOMM Incorporated" },
  { ticker: "SHOP", name: "Shopify Inc." },
  { ticker: "WDAY", name: "Workday, Inc." },
  { ticker: "JPM", name: "JPMorgan Chase & Co." },
  { ticker: "MA", name: "Mastercard Incorporated" },
  { ticker: "WMT", name: "Walmart Inc." },
  { ticker: "SPOT", name: "Spotify Technology S.A." },
  { ticker: "MS", name: "Morgan Stanley" },
  { ticker: "INTC", name: "Intel Corporation" },
  { ticker: "CSCO", name: "Cisco Systems, Inc." },
  { ticker: "PEP", name: "PepsiCo, Inc." },
  { ticker: "COST", name: "Costco Wholesale Corporation" },
  { ticker: "CMCSA", name: "Comcast Corporation" },
  { ticker: "TXN", name: "Texas Instruments Incorporated" },
  { ticker: "GILD", name: "Gilead Sciences, Inc." },
  { ticker: "SBUX", name: "Starbucks Corporation" },
  { ticker: "ISRG", name: "Intuitive Surgical, Inc." },
  { ticker: "MDLZ", name: "Mondelez International, Inc." },
  { ticker: "ADI", name: "Analog Devices, Inc." },
  { ticker: "VRTX", name: "Vertex Pharmaceuticals Incorporated" },
  { ticker: "REGN", name: "Regeneron Pharmaceuticals, Inc." },
  { ticker: "LRCX", name: "Lam Research Corporation" },
  { ticker: "KLAC", name: "KLA Corporation" },
  { ticker: "AEP", name: "American Electric Power Company, Inc." },
  { ticker: "CTAS", name: "Cintas Corporation" },
  { ticker: "MAR", name: "Marriott International, Inc." },
  { ticker: "PANW", name: "Palo Alto Networks, Inc." },
];

// Workflow steps from README
export const WORKFLOW_STEPS: WorkflowStep[] = [
  {
    title: "Trigger – Daily Market Close",
    description:
      "Fires Monday through Friday at 16:05 (respecting the timezone configured on your n8n instance).",
  },
  {
    title: "Prepare Stock List",
    description:
      "Randomly picks five tickers from your curated universe so that the analysis rotates through different symbols.",
  },
  {
    title: "Fetch Market Data",
    description:
      "Retrieves up to 250 daily bars from Alpaca and pulls the latest price and fundamental data from Yahoo Finance.",
  },
  {
    title: "Technical Analysis",
    description:
      "Computes technical indicators (RSI, MACD, ATR, Bollinger Bands, moving averages, MFI, etc.) and generates swing trade recommendations using Gemini AI.",
  },
];

export const STORAGE_KEY = "n8n-trade-subscription";
